# Generated by Django 5.2.6 on 2025-09-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.CharField(max_length=100000)),
                ('answer', models.CharField(max_length=50000)),
            ],
        ),
    ]
