# Generated by Django 5.2.8 on 2025-12-11 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wrong_questions_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WrongQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('wrong_questions_data', models.JSONField()),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.quizzes')),
            ],
        ),
    ]
